In [70]:
!pip install numpy pandas matplotlib scikit-learn

In [71]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [72]:
df = pd.read_csv('Solar_radiation_classification.csv')
df

Air Temperature (C°)  Air Temperature Uncertainty (C°)  \
0                 1.598833                         -0.039841   
1                 1.415552                         -0.039841   
2                 1.034891                         -0.039841   
3                 0.174880                         -0.039841   
4                -0.572343                         -0.039841   
...                    ...                               ...   
1257             -0.078894                         -0.039841   
1258             -0.177584                         -0.039841   
1259              0.865709                         -0.039841   
1260              1.105384                         -0.039841   
1261              1.387355                         -0.039841   

      Wind Direction at 3m (°N)  Wind Direction at 3m Uncertainty (°N)  \
0                     -1.358521                               0.163933   
1                     -1.333544                               0.163933   
2                     -1.241959                               0.163933   
3                     -1.075441                               0.163933   
4                     -0.883946                               0.163933   
...                         ...                                    ...   
1257                  -0.684124                               0.163933   
1258                  -0.484303                              -0.860649   
1259                  -0.717428                               0.163933   
1260                  -0.542584                               0.163933   
1261                   1.180875                               0.163933   

      Wind Speed at 3m (m/s)  Wind Speed at 3m Uncertainty (m/s)  \
0                  -0.351941                            0.677977   
1                  -0.460051                           -1.548603   
2                  -0.784380                           -1.548603   
3                  -1.000600                           -1.548603   
4                  -0.892490                           -1.548603   
...                      ...                                 ...   
1257                0.404827                            0.677977   
1258               -0.027612                            0.677977   
1259               -0.784380                           -1.548603   
1260               -0.892490                            0.677977   
1261               -0.568161                            0.677977   

      Wind Speed at 3m (std dev) (m/s)  DHI (Wh/m2)  DHI Uncertainty (Wh/m2)  \
0                            -0.309934     2.087472                 2.420683   
1                            -0.731123     0.780151                 1.294103   
2                            -1.152311     0.093343                 0.300212   
3                            -1.152311    -0.634539                -0.039165   
4                            -0.731123    -0.993174                -0.147613   
...                                ...          ...                      ...   
1257                          0.532442     0.986483                -0.909298   
1258                         -0.099340     0.656518                -0.882505   
1259                         -0.309934     1.935721                -0.643920   
1260                         -0.309934     1.485567                -0.871022   
1261                          0.111254     1.499488                -0.775333   

      Standard Deviation DHI (Wh/m2)  ...  GHI Uncertainty (Wh/m2)  \
0                      -3.161415e-15  ...                 0.645691   
1                      -3.161415e-15  ...                 0.693011   
2                      -3.161415e-15  ...                 0.194101   
3                      -3.161415e-15  ...                -0.002891   
4                      -3.161415e-15  ...                -0.071556   
...                              ...  ...                      ...   
1257                    3.745790e-01  ...                -0.570980   
1258      

In [73]:
# Remove regression column and retain classification column
df.drop(['GHI (Wh/m2)'], axis=1, inplace=True)
df.columns

Index(['Air Temperature (C°)', 'Air Temperature Uncertainty (C°)',
       'Wind Direction at 3m (°N)', 'Wind Direction at 3m Uncertainty (°N)',
       'Wind Speed at 3m (m/s)', 'Wind Speed at 3m Uncertainty (m/s)',
       'Wind Speed at 3m (std dev) (m/s)', 'DHI (Wh/m2)',
       'DHI Uncertainty (Wh/m2)', 'Standard Deviation DHI (Wh/m2)',
       'DNI (Wh/m2)', 'DNI Uncertainty (Wh/m2)',
       'Standard Deviation DNI (Wh/m2)', 'GHI Uncertainty (Wh/m2)',
       'Standard Deviation GHI (Wh/m2)', 'Peak Wind Speed at 3m (m/s)',
       'Peak Wind Speed at 3m Uncertainty (m/s)', 'Relative Humidity (%)',
       'Relative Humidity Uncertainty (%)',
       'Barometric Pressure (mB (hPa equiv))',
       'Barometric Pressure Uncertainty (mB (hPa equiv))', 'Class'],
      dtype='object')

In [74]:
y = df.pop('Class').values
X = df.values

print('Number of examples: ', X.shape[0])
print('Number of variables: ', X.shape[1])

Number of examples:  1262
Number of variables:  21


In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)
print('Number of training examples: ', X_train.shape[0])
print('Number of testing examples: ', X_test.shape[0])

Number of training examples:  1009
Number of testing examples:  253


In [76]:
clf = SVC(C=1.0, kernel='rbf', degree=2, gamma='scale')
clf.fit(X_train, y_train)

SVC(degree=2)

In [77]:
?SVC

Init signature:
SVC(
    *,
    C=1.0,
    kernel='rbf',
    degree=3,
    gamma='scale',
    coef0=0.0,
    shrinking=True,
    probability=False,
    tol=0.001,
    cache_size=200,
    class_weight=None,
    verbose=False,
    max_iter=-1,
    decision_function_shape='ovr',
    break_ties=False,
    random_state=None,
)
Docstring:     
C-Support Vector Classification.

The implementation is based on libsvm. The fit time scales at least
quadratically with the number of samples and may be impractical
beyond tens of thousands of samples. For large datasets
consider using :class:`~sklearn.svm.LinearSVC` or
:class:`~sklearn.linear_model.SGDClassifier` instead, possibly after a
:class:`~sklearn.kernel_approximation.Nystroem` transformer or
other :ref:`kernel_approximation`.

The multiclass support is handled according to a one-vs-one scheme.

For details on the precise mathematical formulation of the provided
kernel functions and how `gamma`, `coef0` and `degree` affect each
other, see the

In [78]:
y_test_pred = clf.predict(X_test)
y_test_pred

array(['Monitoring', 'Monitoring', 'Inspecting', 'Monitoring',
       'Inspecting', 'Monitoring', 'Monitoring', 'Monitoring', 'Running',
       'Monitoring', 'Monitoring', 'Running', 'Running', 'Inspecting',
       'Running', 'Running', 'Monitoring', 'Inspecting', 'Running',
       'Monitoring', 'Monitoring', 'Monitoring', 'Monitoring',
       'Inspecting', 'Running', 'Inspecting', 'Monitoring', 'Inspecting',
       'Monitoring', 'Monitoring', 'Running', 'Monitoring', 'Monitoring',
       'Monitoring', 'Monitoring', 'Running', 'Running', 'Monitoring',
       'Running', 'Monitoring', 'Monitoring', 'Running', 'Monitoring',
       'Running', 'Running', 'Running', 'Monitoring', 'Running',
       'Running', 'Monitoring', 'Monitoring', 'Inspecting', 'Running',
       'Monitoring', 'Running', 'Monitoring', 'Running', 'Running',
       'Monitoring', 'Monitoring', 'Monitoring', 'Running', 'Monitoring',
       'Monitoring', 'Monitoring', 'Running', 'Monitoring', 'Running',
       'Monitoring', '

### Measure accuracy 

In [79]:
y_train_pred = clf.predict(X_train)
acc = sum(y_train_pred == y_train)/y_train_pred.shape[0] *100
print('Training accuracy: {0:2.2f}%'.format(acc))

Training accuracy: 94.95%


In [80]:
acc = sum(y_test_pred == y_test)/y_test_pred.shape[0] *100
print('Testing accuracy: {0:2.2f}%'.format(acc))

Testing accuracy: 92.89%


In [81]:
clf.n_support_, clf.classes_

(array([117, 267, 158]),
 array(['Inspecting', 'Monitoring', 'Running'], dtype=object))

In [82]:
clf.support_

array([   3,   20,   22,   24,   32,   40,   49,   50,   51,   53,   54,
         69,   70,   75,   80,   95,  118,  141,  159,  160,  162,  167,
        185,  202,  205,  232,  238,  247,  254,  255,  256,  257,  259,
        279,  281,  291,  298,  305,  306,  328,  351,  356,  364,  369,
        378,  389,  393,  401,  402,  423,  457,  466,  469,  477,  486,
        494,  495,  523,  526,  530,  534,  541,  542,  556,  574,  582,
        584,  588,  599,  603,  605,  607,  623,  632,  638,  644,  657,
        667,  669,  680,  681,  682,  691,  695,  696,  700,  702,  715,
        723,  739,  746,  747,  756,  763,  773,  775,  784,  792,  794,
        809,  814,  829,  833,  847,  849,  857,  873,  883,  896,  900,
        904,  908,  927,  943,  953,  977,  985,    0,    1,    4,   12,
         14,   19,   27,   28,   30,   37,   38,   41,   42,   46,   55,
         58,   59,   67,   68,   73,   76,   84,   85,   89,   94,   99,
        100,  106,  108,  116,  119,  120,  122,  1

In [83]:
clf.support_vectors_

array([[-1.07989059, -0.03984095,  1.2558075 , ..., -0.04948017,
        -0.59347289, -0.7833155 ],
       [-0.03659813, -0.03984095, -1.30856588, ..., -0.04948017,
         0.99883342,  0.89218308],
       [-0.02249958, -0.03984095,  0.05687969, ..., -0.04948017,
         1.24413466,  1.31105772],
       ...,
       [ 0.17488007, -0.03984095,  0.8561649 , ..., -0.04948017,
        -2.33640278, -2.45881408],
       [ 0.56963938, -0.03984095, -1.47508363, ..., -0.04948017,
         0.88909339,  0.89218308],
       [ 0.80931468, -0.03984095, -1.20032934, ..., -0.04948017,
        -0.87965768, -0.7833155 ]])

In [84]:
clf.decision_function

<bound method BaseSVC.decision_function of SVC(degree=2)>