In [1]:
import numpy as np

In [50]:
X = np.array([[2, 4, 3, 1, 2],
              [5, 6, 2, 2, 4]]).T
X

array([[2, 5],
       [4, 6],
       [3, 2],
       [1, 2],
       [2, 4]])

#### Mean normalization

In [51]:
X_mean = np.mean(X, axis=0)
X_mean

array([2.4, 3.8])

In [52]:
X_norm = X - X_mean
X_norm

array([[-0.4,  1.2],
       [ 1.6,  2.2],
       [ 0.6, -1.8],
       [-1.4, -1.8],
       [-0.4,  0.2]])

In [53]:
C = np.cov(X_norm.T)
C

array([[1.3, 1.1],
       [1.1, 3.2]])

In [54]:
C[0][0] = np.mean(X_norm[:, 0] * X_norm[:, 0])
C[0][1] = np.mean(X_norm[:, 0] * X_norm[:, 1])
C[1][0] = C[0][1]
C[1][1] = np.mean(X_norm[:, 1] * X_norm[:, 1])
C

array([[1.04, 0.88],
       [0.88, 2.56]])

In [17]:
eig_val, eig_vec = np.linalg.eig(C)
eig_val, eig_vec

(array([0.63724465, 2.96275535]),
 array([[-0.9092909, -0.4161611],
        [ 0.4161611, -0.9092909]]))

In [23]:
eig_vec[:, np.argmax(eig_val)]

(2,)

In [27]:
eig_vec @ X_norm.T

array([[-0.13567697, -2.37041986,  0.20351545,  2.02209724,  0.28048414],
       [-1.25761352, -1.33458221,  1.88642028,  1.05409807, -0.34832262]])

In [26]:
eig_vec[:, np.argmax(eig_val)] @ X_norm.T

array([-0.92468463, -2.66629774,  1.38702695,  2.21934916, -0.01539374])