In [1]:
import numpy as np

## OR

In [2]:
## Input
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).T
print('Input:\n', x)
print('Shape:', x.shape)

Input:
 [[0 0 1 1]
 [0 1 0 1]]
Shape: (2, 4)


In [3]:
## Output
y = np.array([[0, 1, 1, 1]])
print('Output:\n', y)
print('Shape:', y.shape)

Output:
 [[0 1 1 1]]
Shape: (1, 4)


In [4]:
## Add bias
X = np.vstack((np.ones((1, x.shape[1])), x))
print('Input:\n', X)
print('Shape:', X.shape)

Input:
 [[1. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 1. 0. 1.]]
Shape: (3, 4)


In [5]:
## weight vector
w = np.array([[0],[1],[1]])
print('Weight:\n', w)
print('Shape:', w.shape)

Weight:
 [[0]
 [1]
 [1]]
Shape: (3, 1)


In [6]:
## Prediction
net = (w.T @ X).ravel()
print('net=', net)
y_pred = [int(op>0) for op in net]
print('Predicted output:', y_pred)

net= [0. 1. 1. 2.]
Predicted output: [0, 1, 1, 1]


## AND

In [23]:
## Input
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).T
print('Input:\n', x)
print('Shape:', x.shape)

Input:
 [[0 0 1 1]
 [0 1 0 1]]
Shape: (2, 4)


In [24]:
## Add bias
X = np.vstack((np.ones((1, x.shape[1])), x))
print('Input:\n', X)
print('Shape:', X.shape)

Input:
 [[1. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 1. 0. 1.]]
Shape: (3, 4)


In [25]:
## Output
y = np.array([[0, 0, 0, 1]])
print('Output:\n', y)
print('Shape:', y.shape)

Output:
 [[0 0 0 1]]
Shape: (1, 4)


In [26]:
## weight vector
w = np.array([[-1],[1],[1]])
print('Weight:\n', w)
print('Shape:', w.shape)

Weight:
 [[-1]
 [ 1]
 [ 1]]
Shape: (3, 1)


In [27]:
## Prediction
net = (w.T @ X).ravel()
print('net=', net)
y_pred = [int(op>0) for op in net]
print('Predicted output:', y_pred)

net= [-1.  0.  0.  1.]
Predicted output: [0, 0, 0, 1]


## NOT

In [28]:
## Input
x = np.array([[0], [1]]).T
print('Input:\n', x)
print('Shape:', x.shape)

Input:
 [[0 1]]
Shape: (1, 2)


In [29]:
## Add bias
X = np.vstack((np.ones((1, x.shape[1])), x))
print('Input:\n', X)
print('Shape:', X.shape)

Input:
 [[1. 1.]
 [0. 1.]]
Shape: (2, 2)


In [30]:
## Output
y = np.array([[1, 0]])
print('Output:\n', y)
print('Shape:', y.shape)

Output:
 [[1 0]]
Shape: (1, 2)


In [31]:
## weight vector
w = np.array([[1],[-1]])
print('Weight:\n', w)
print('Shape:', w.shape)

Weight:
 [[ 1]
 [-1]]
Shape: (2, 1)


In [32]:
## Prediction
net = (w.T @ X).ravel()
print('net=', net)
y_pred = [int(op>0) for op in net]
print('Predicted output:', y_pred)

net= [1. 0.]
Predicted output: [1, 0]
